import Fastify from 'fastify';
import cors from '@fastify/cors';
import cookie from '@fastify/cookie';
import jwt from '@fastify/jwt';
import multipart from '@fastify/multipart';
import rateLimit from '@fastify/rate-limit';
import argon2 from 'argon2';
import { randomUUID } from 'node:crypto';
import mammoth from 'mammoth';
import pdf from 'pdf-parse';
import { z } from 'zod';
import { many, migrate, one, pool } from './db.js';
import { chunkText, fetchPublicPage } from './knowledge.js';
import { answerWithKnowledge } from './llm.js';

const app = Fastify({ logger: true, bodyLimit: 8 * 1024 * 1024 });
await app.register(cors,{origin:process.env.FRONTEND_ORIGIN||'http://localhost:5173',credentials:true});
await app.register(cookie);
await app.register(jwt,{secret:process.env.JWT_SECRET||'development-only-secret-change-me-123456789'});
await app.register(multipart,{limits:{fileSize:7*1024*1024,files:1}});
await app.register(rateLimit,{max:120,timeWindow:'1 minute'});

type Session={userId:string;workspaceId:string};
const uuid=()=>randomUUID();
const publicId=()=>`agt_${uuid().replace(/-/g,'').slice(0,20)}`;
const mapAgent=(r:any)=>({id:r.id,name:r.name,description:r.description,instructions:r.instructions,tone:r.tone,greeting:r.greeting,primaryColor:r.primary_color,position:r.position,publicId:r.public_id,status:r.status,createdAt:r.created_at});
async function auth(req:any,reply:any){try{const token=req.cookies.session;if(!token)throw 0;req.session=app.jwt.verify<Session>(token)}catch{return reply.code(401).send({error:'Unauthorized'})}}
function setSession(reply:any,payload:Session){reply.setCookie('session',app.jwt.sign(payload,{expiresIn:'7d'}),{httpOnly:true,sameSite:'lax',secure:process.env.COOKIE_SECURE==='true',path:'/',maxAge:604800})}
async function ownedAgent(id:string,w:string){return one<any>('select * from agents where id=$1 and workspace_id=$2',[id,w])}
async function saveSource(w:string,a:string,name:string,kind:string,raw:string,url?:string){const id=uuid();await pool.query('insert into knowledge_sources(id,workspace_id,agent_id,name,kind,source_url,raw_text) values($1,$2,$3,$4,$5,$6,$7)',[id,w,a,name,kind,url||null,raw]);const chunks=chunkText(raw);for(let i=0;i<chunks.length;i++)await pool.query('insert into knowledge_chunks(id,source_id,agent_id,content,chunk_index) values($1,$2,$3,$4,$5)',[uuid(),id,a,chunks[i],i]);return one<any>('select id,agent_id,name,kind,status,created_at from knowledge_sources where id=$1',[id])}
async function chatAnswer(agent:any,question:string,history:any[]=[]){let chunks=await many<any>(`select kc.content,ks.name source,ts_rank(kc.search,websearch_to_tsquery('english',$2)) rank from knowledge_chunks kc join knowledge_sources ks on ks.id=kc.source_id where kc.agent_id=$1 and kc.search @@ websearch_to_tsquery('english',$2) order by rank desc limit 6`,[agent.id,question]);if(!chunks.length)chunks=await many<any>('select kc.content,ks.name source from knowledge_chunks kc join knowledge_sources ks on ks.id=kc.source_id where kc.agent_id=$1 order by ks.created_at desc,kc.chunk_index limit 4',[agent.id]);return answerWithKnowledge({agentName:agent.name,instructions:agent.instructions,tone:agent.tone,question,history,chunks})}

app.get('/health',async()=>({ok:true}));
app.post('/api/auth/signup',async(req,reply)=>{const b=z.object({name:z.string().min(2).max(80),email:z.string().email(),password:z.string().min(8).max(200)}).parse(req.body),email=b.email.toLowerCase();if(await one('select id from users where email=$1',[email]))return reply.code(409).send({error:'Email already registered'});const c=await pool.connect();try{await c.query('begin');const userId=uuid(),workspaceId=uuid();await c.query('insert into users(id,name,email,password_hash) values($1,$2,$3,$4)',[userId,b.name,email,await argon2.hash(b.password)]);await c.query('insert into workspaces(id,owner_user_id,name,support_email) values($1,$2,$3,$4)',[workspaceId,userId,`${b.name}'s workspace`,email]);await c.query("insert into workspace_members(workspace_id,user_id,role) values($1,$2,'owner')",[workspaceId,userId]);await c.query('commit');setSession(reply,{userId,workspaceId});return {user:{id:userId,name:b.name,email,workspaceId}}}catch(e){await c.query('rollback');throw e}finally{c.release()}});
app.post('/api/auth/login',async(req,reply)=>{const b=z.object({email:z.string().email(),password:z.string().min(1)}).parse(req.body);const r=await one<any>("select u.*,wm.workspace_id from users u join workspace_members wm on wm.user_id=u.id where u.email=$1 order by case when wm.role='owner' then 0 else 1 end limit 1",[b.email.toLowerCase()]);if(!r||!await argon2.verify(r.password_hash,b.password))return reply.code(401).send({error:'Invalid email or password'});setSession(reply,{userId:r.id,workspaceId:r.workspace_id});return {user:{id:r.id,name:r.name,email:r.email,workspaceId:r.workspace_id}}});
app.post('/api/auth/logout',async(_r,reply)=>{reply.clearCookie('session',{path:'/'});return {ok:true}});
app.get('/api/auth/me',{preHandler:auth},async(req:any)=>({user:{...(await one<any>('select id,name,email from users where id=$1',[req.session.userId])),workspaceId:req.session.workspaceId}}));

app.get('/api/agents',{preHandler:auth},async(req:any)=>({agents:(await many<any>('select * from agents where workspace_id=$1 order by created_at desc',[req.session.workspaceId])).map(mapAgent)}));
app.post('/api/agents',{preHandler:auth},async(req:any)=>{const b=z.object({name:z.string().min(2).max(80),description:z.string().max(500).optional()}).parse(req.body),id=uuid();await pool.query('insert into agents(id,workspace_id,name,description,public_id) values($1,$2,$3,$4,$5)',[id,req.session.workspaceId,b.name,b.description||'',publicId()]);return {agent:mapAgent(await one<any>('select * from agents where id=$1',[id]))}});
app.get('/api/agents/:id',{preHandler:auth},async(req:any,reply)=>{const a=await ownedAgent(req.params.id,req.session.workspaceId);return a?{agent:mapAgent(a)}:reply.code(404).send({error:'Agent not found'})});
app.patch('/api/agents/:id',{preHandler:auth},async(req:any,reply)=>{const b=z.object({name:z.string().min(2).max(80).optional(),description:z.string().max(500).optional(),instructions:z.string().max(5000).optional(),tone:z.string().max(80).optional(),greeting:z.string().max(300).optional(),primaryColor:z.string().regex(/^#[0-9A-Fa-f]{6}$/).optional(),position:z.enum(['left','right']).optional(),status:z.enum(['draft','live']).optional()}).parse(req.body),a=await ownedAgent(req.params.id,req.session.workspaceId);if(!a)return reply.code(404).send({error:'Agent not found'});const n={...a,name:b.name??a.name,description:b.description??a.description,instructions:b.instructions??a.instructions,tone:b.tone??a.tone,greeting:b.greeting??a.greeting,primary_color:b.primaryColor??a.primary_color,position:b.position??a.position,status:b.status??a.status};await pool.query('update agents set name=$1,description=$2,instructions=$3,tone=$4,greeting=$5,primary_color=$6,position=$7,status=$8,updated_at=now() where id=$9 and workspace_id=$10',[n.name,n.description,n.instructions,n.tone,n.greeting,n.primary_color,n.position,n.status,req.params.id,req.session.workspaceId]);return {agent:mapAgent(await ownedAgent(req.params.id,req.session.workspaceId))}});
app.delete('/api/agents/:id',{preHandler:auth},async(req:any)=>{await pool.query('delete from agents where id=$1 and workspace_id=$2',[req.params.id,req.session.workspaceId]);return {ok:true}});
app.post('/api/agents/:id/test-chat',{preHandler:auth},async(req:any,reply)=>{const {message}=z.object({message:z.string().min(1).max(2000)}).parse(req.body),a=await ownedAgent(req.params.id,req.session.workspaceId);if(!a)return reply.code(404).send({error:'Agent not found'});const r=await chatAnswer(a,message);return {message:{id:uuid(),role:'assistant',content:r.answer,createdAt:new Date().toISOString()},citations:r.citations}});

app.get('/api/agents/:id/knowledge',{preHandler:auth},async(req:any,reply)=>{if(!await ownedAgent(req.params.id,req.session.workspaceId))return reply.code(404).send({error:'Agent not found'});const rs=await many<any>('select id,agent_id,name,kind,status,created_at from knowledge_sources where agent_id=$1 and workspace_id=$2 order by created_at desc',[req.params.id,req.session.workspaceId]);return {sources:rs.map(r=>({id:r.id,agentId:r.agent_id,name:r.name,kind:r.kind,status:r.status,createdAt:r.created_at}))}});
app.post('/api/agents/:id/knowledge/text',{preHandler:auth},async(req:any,reply)=>{const b=z.object({name:z.string().min(2).max(120),text:z.string().min(20).max(500000)}).parse(req.body);if(!await ownedAgent(req.params.id,req.session.workspaceId))return reply.code(404).send({error:'Agent not found'});return {source:await saveSource(req.session.workspaceId,req.params.id,b.name,'text',b.text)}});
app.post('/api/agents/:id/knowledge/url',{preHandler:auth},async(req:any,reply)=>{const {url}=z.object({url:z.string().url()}).parse(req.body);if(!await ownedAgent(req.params.id,req.session.workspaceId))return reply.code(404).send({error:'Agent not found'});const raw=await fetchPublicPage(url);if(raw.length<20)return reply.code(400).send({error:'No usable text found'});return {source:await saveSource(req.session.workspaceId,req.params.id,new URL(url).hostname,'url',raw,url)}});
app.post('/api/agents/:id/knowledge/file',{preHandler:auth},async(req:any,reply)=>{if(!await ownedAgent(req.params.id,req.session.workspaceId))return reply.code(404).send({error:'Agent not found'});const part=await req.file();if(!part)return reply.code(400).send({error:'Choose a file'});const buf=await part.toBuffer(),name=part.filename.toLowerCase();let raw='';if(name.endsWith('.pdf'))raw=(await pdf(buf)).text;else if(name.endsWith('.docx'))raw=(await mammoth.extractRawText({buffer:buf})).value;else if(name.endsWith('.txt')||name.endsWith('.md'))raw=buf.toString('utf8');else return reply.code(400).send({error:'Supported files: PDF, DOCX, TXT and MD'});if(raw.trim().length<20)return reply.code(400).send({error:'Not enough readable text'});return {source:await saveSource(req.session.workspaceId,req.params.id,part.filename,'file',raw.slice(0,500000))}});
app.delete('/api/agents/:id/knowledge/:sourceId',{preHandler:auth},async(req:any)=>{await pool.query('delete from knowledge_sources where id=$1 and agent_id=$2 and workspace_id=$3',[req.params.sourceId,req.params.id,req.session.workspaceId]);return {ok:true}});

app.get('/api/conversations',{preHandler:auth},async(req:any)=>{const rs=await many<any>(`select c.id,c.agent_id,a.name agent_name,c.visitor_label,c.last_message_at,count(m.id)::int message_count from conversations c join agents a on a.id=c.agent_id left join messages m on m.conversation_id=c.id where c.workspace_id=$1 group by c.id,a.name order by c.last_message_at desc limit 200`,[req.session.workspaceId]);return {conversations:rs.map(r=>({id:r.id,agentId:r.agent_id,agentName:r.agent_name,visitorLabel:r.visitor_label,messageCount:r.message_count,lastMessageAt:r.last_message_at}))}});
app.get('/api/conversations/:id/messages',{preHandler:auth},async(req:any,reply)=>{if(!await one('select id from conversations where id=$1 and workspace_id=$2',[req.params.id,req.session.workspaceId]))return reply.code(404).send({error:'Conversation not found'});const rs=await many<any>('select id,role,content,created_at from messages where conversation_id=$1 order by created_at',[req.params.id]);return {messages:rs.map(r=>({id:r.id,role:r.role,content:r.content,createdAt:r.created_at}))}});
app.get('/api/leads',{preHandler:auth},async(req:any)=>{const rs=await many<any>('select l.*,a.name agent_name from leads l join agents a on a.id=l.agent_id where l.workspace_id=$1 order by l.created_at desc',[req.session.workspaceId]);return {leads:rs.map(r=>({id:r.id,agentId:r.agent_id,agentName:r.agent_name,name:r.name,email:r.email,phone:r.phone,createdAt:r.created_at}))}});
app.get('/api/analytics/overview',{preHandler:auth},async(req:any)=>{const w=req.session.workspaceId,c=await one<any>(`select (select count(*) from agents where workspace_id=$1)::int agents,(select count(*) from conversations where workspace_id=$1)::int conversations,(select count(*) from messages m join conversations c on c.id=m.conversation_id where c.workspace_id=$1)::int messages,(select count(*) from leads where workspace_id=$1)::int leads,(select count(*) from knowledge_sources where workspace_id=$1)::int sources`,[w]),daily=await many<any>(`select to_char(d,'YYYY-MM-DD') day,coalesce(x.count,0)::int conversations from generate_series(current_date-13,current_date,'1 day') d left join (select date(created_at) day,count(*)::int count from conversations where workspace_id=$1 and created_at>=current_date-13 group by 1)x on x.day=d::date order by d`,[w]);return {...c,daily}});
app.get('/api/integrations',{preHandler:auth},async(req:any)=>{const labels:any={whatsapp:'WhatsApp Business',zoho:'Zoho CRM',webhook:'Webhook'},rs=await many<any>('select provider,enabled from integrations where workspace_id=$1',[req.session.workspaceId]),m=new Map(rs.map(r=>[r.provider,r.enabled]));return {integrations:Object.entries(labels).map(([provider,label])=>({provider,label,enabled:Boolean(m.get(provider))}))}});
app.put('/api/integrations/:provider',{preHandler:auth},async(req:any)=>{const provider=z.enum(['whatsapp','zoho','webhook']).parse(req.params.provider),{enabled}=z.object({enabled:z.boolean()}).parse(req.body);await pool.query('insert into integrations(workspace_id,provider,enabled) values($1,$2,$3) on conflict(workspace_id,provider) do update set enabled=excluded.enabled',[req.session.workspaceId,provider,enabled]);return {integration:{provider,enabled}}});
app.get('/api/workspace/settings',{preHandler:auth},async(req:any)=>{const r=await one<any>('select name,support_email,timezone from workspaces where id=$1',[req.session.workspaceId]);return {settings:{name:r.name,supportEmail:r.support_email,timezone:r.timezone}}});
app.put('/api/workspace/settings',{preHandler:auth},async(req:any)=>{const b=z.object({name:z.string().min(2).max(120),supportEmail:z.union([z.string().email(),z.literal('')]),timezone:z.string().min(1).max(100)}).parse(req.body);await pool.query('update workspaces set name=$1,support_email=$2,timezone=$3 where id=$4',[b.name,b.supportEmail,b.timezone,req.session.workspaceId]);return {settings:b}});

app.get('/api/public/agents/:publicId',async(req:any,reply)=>{const a=await one<any>('select name,greeting,primary_color,position,public_id,status from agents where public_id=$1',[req.params.publicId]);return a&&a.status==='live'?{agent:{name:a.name,greeting:a.greeting,primaryColor:a.primary_color,position:a.position,publicId:a.public_id}}:reply.code(404).send({error:'Chatbot is not live'})});
app.post('/api/public/chat/:publicId',{config:{rateLimit:{max:30,timeWindow:'1 minute'}}},async(req:any,reply)=>{const b=z.object({conversationId:z.string().uuid().optional(),message:z.string().min(1).max(2000)}).parse(req.body),a=await one<any>("select * from agents where public_id=$1 and status='live'",[req.params.publicId]);if(!a)return reply.code(404).send({error:'Chatbot unavailable'});let cid=b.conversationId;if(!cid||!await one('select id from conversations where id=$1 and agent_id=$2',[cid,a.id])){cid=uuid();await pool.query('insert into conversations(id,workspace_id,agent_id) values($1,$2,$3)',[cid,a.workspace_id,a.id])}await pool.query("insert into messages(id,conversation_id,role,content) values($1,$2,'user',$3)",[uuid(),cid,b.message]);const h=await many<any>('select role,content from messages where conversation_id=$1 order by created_at desc limit 7',[cid]);let result;try{result=await chatAnswer(a,b.message,h.reverse())}catch(e){req.log.error(e);return reply.code(502).send({error:'AI provider temporarily unavailable'})}const mid=uuid();await pool.query("insert into messages(id,conversation_id,role,content) values($1,$2,'assistant',$3)",[mid,cid,result.answer]);await pool.query('update conversations set last_message_at=now() where id=$1',[cid]);return {conversationId:cid,message:{id:mid,role:'assistant',content:result.answer,createdAt:new Date().toISOString()},citations:result.citations}});
app.post('/api/public/leads/:publicId',{config:{rateLimit:{max:10,timeWindow:'1 minute'}}},async(req:any,reply)=>{const b=z.object({name:z.string().min(2).max(100),email:z.string().email(),phone:z.string().max(50).optional()}).parse(req.body),a=await one<any>("select id,workspace_id from agents where public_id=$1 and status='live'",[req.params.publicId]);if(!a)return reply.code(404).send({error:'Chatbot unavailable'});const id=uuid();await pool.query('insert into leads(id,workspace_id,agent_id,name,email,phone) values($1,$2,$3,$4,$5,$6)',[id,a.workspace_id,a.id,b.name,b.email,b.phone||'']);return {leadId:id}});
app.get('/widget.js',async(_r,reply)=>reply.type('application/javascript').header('cache-control','public,max-age=300').send(`(()=>{const s=document.currentScript,id=s?.dataset.agent;if(!id)return;const b=new URL(s.src).origin;fetch(b+'/api/public/agents/'+id).then(r=>r.json()).then(({agent})=>{const side=agent.position==='left'?'left':'right',btn=document.createElement('button'),f=document.createElement('iframe');btn.textContent='✦';btn.setAttribute('aria-label','Open chat');btn.style.cssText='position:fixed;'+side+':18px;bottom:18px;width:58px;height:58px;border:0;border-radius:18px;background:'+agent.primaryColor+';color:#fff;font:700 22px system-ui;box-shadow:0 14px 38px #0003;cursor:pointer;z-index:2147483647';f.src=b+'/widget/'+id;f.title=agent.name;f.style.cssText='position:fixed;'+side+':18px;bottom:88px;width:min(420px,calc(100vw - 36px));height:min(700px,calc(100vh - 120px));border:0;border-radius:18px;box-shadow:0 20px 60px #0003;z-index:2147483646;background:#fff;display:none';btn.onclick=()=>f.style.display=f.style.display==='none'?'block':'none';document.body.append(f,btn)}).catch(()=>{})})()`));
app.setErrorHandler((e,_req,reply)=>{if(e instanceof z.ZodError)return reply.code(400).send({error:e.issues[0]?.message||'Invalid input'});app.log.error(e);reply.code(500).send({error:'Unexpected server error'})});
await migrate();
await app.listen({port:Number(process.env.PORT||8080),host:'0.0.0.0'});
